#!/usr/bin/env bash

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

# cd to project root
cd "$(dirname "$0")/.."

# run tests
script/test
