#!/usr/bin/env bash

# script/postbuild: Cleanup environment after CI. This is primarily
#                   designed to run on the continuous integration server.

set -e

PROJECT_NAME='spokes'

[[ "${PROJECT_NAME:-}" ]] || (echo "PROJECT_NAME is required." && exit 1)

# cd to project root
cd "$(dirname "$0")/.."

docker stop `docker ps -a -q -f status=exited` &> /dev/null || true &> /dev/null
docker rm -v `docker ps -a -q -f status=exited` &> /dev/null || true &> /dev/null
docker rmi `docker images --filter 'dangling=true' -q --no-trunc` &> /dev/null || true &> /dev/null
